name: Build workflow

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:

  test:
    name: Tests verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: composer tests

  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=LukaMrt_Parraindex
            -Dsonar.organization=lukamrt
            -Dsonar.sources=.

  deploy-develop:
    name: Deploy to development environment
    needs: test
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'cd /var/www/dev.lukamaret.com &&
            git checkout develop &&
            git pull &&
            composer update &&
            composer install --no-interaction --prefer-dist --optimize-autoloader &&
            sass --update scss:public/css'

  deploy-production:
    name: Deploy to production environment
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'cd /var/www/parraindex.lukamaret.com &&
            git checkout main &&
            git pull &&
            composer update && composer install --no-interaction --prefer-dist --optimize-autoloader &&
            sass --update scss:public/css'
